version: "3.6"

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "neo4j-vol:/data"
      - "neo4j-vol:/logs"
      - "neo4j-vol:/var/lib/neo4j/import"
      - "neo4j-vol:/plugins"
    environment:
      - NEO4J_AUTH=none

volumes:
  neo4j-vol:
    driver: local
